exemplo_grape_api/config/routes.rb
Rails.application.routes.draw do
  mount API::V1 => '/'
  resources :contatos
  resources :operadoras

end

exemplo_grape_api/app/models/contato.rb
class Contato < ActiveRecord::Base
  belongs_to :operadora
end

exemplo_grape_api/app/models/operadora.rb
class Operadora < ActiveRecord::Base
end

exemplo_grape_api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

exemplo_grape_api/app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  before_action :set_contato, only: [:show, :edit, :update, :destroy]

  # GET /contatos
  # GET /contatos.json
  def index
    @contatos = Contato.all
  end

  # GET /contatos/1
  # GET /contatos/1.json
  def show
  end

  # GET /contatos/new
  def new
    @contato = Contato.new
  end

  # GET /contatos/1/edit
  def edit
  end

  # POST /contatos
  # POST /contatos.json
  def create
    @contato = Contato.new(contato_params)

    respond_to do |format|
      if @contato.save
        format.html { redirect_to @contato, notice: 'Contato was successfully created.' }
        format.json { render :show, status: :created, location: @contato }
      else
        format.html { render :new }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contatos/1
  # PATCH/PUT /contatos/1.json
  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.html { redirect_to @contato, notice: 'Contato was successfully updated.' }
        format.json { render :show, status: :ok, location: @contato }
      else
        format.html { render :edit }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatos/1
  # DELETE /contatos/1.json
  def destroy
    @contato.destroy
    respond_to do |format|
      format.html { redirect_to contatos_url, notice: 'Contato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = Contato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contato_params
      params.require(:contato).permit(:nome, :telefone, :operadora_id, :data)
    end
end

exemplo_grape_api/app/controllers/operadoras_controller.rb
class OperadorasController < ApplicationController
  before_action :set_operadora, only: [:show, :edit, :update, :destroy]

  # GET /operadoras
  # GET /operadoras.json
  def index
    @operadoras = Operadora.all
  end

  # GET /operadoras/1
  # GET /operadoras/1.json
  def show
  end

  # GET /operadoras/new
  def new
    @operadora = Operadora.new
  end

  # GET /operadoras/1/edit
  def edit
  end

  # POST /operadoras
  # POST /operadoras.json
  def create
    @operadora = Operadora.new(operadora_params)

    respond_to do |format|
      if @operadora.save
        format.html { redirect_to @operadora, notice: 'Operadora was successfully created.' }
        format.json { render :show, status: :created, location: @operadora }
      else
        format.html { render :new }
        format.json { render json: @operadora.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operadoras/1
  # PATCH/PUT /operadoras/1.json
  def update
    respond_to do |format|
      if @operadora.update(operadora_params)
        format.html { redirect_to @operadora, notice: 'Operadora was successfully updated.' }
        format.json { render :show, status: :ok, location: @operadora }
      else
        format.html { render :edit }
        format.json { render json: @operadora.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operadoras/1
  # DELETE /operadoras/1.json
  def destroy
    @operadora.destroy
    respond_to do |format|
      format.html { redirect_to operadoras_url, notice: 'Operadora was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operadora
      @operadora = Operadora.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operadora_params
      params.require(:operadora).permit(:nome, :codigo, :categoria, :preco)
    end
end

exemplo_grape_api/app/helpers/application_helper.rb
module ApplicationHelper
end

exemplo_grape_api/app/helpers/contatos_helper.rb
module ContatosHelper
end

exemplo_grape_api/app/helpers/operadoras_helper.rb
module OperadorasHelper
end

exemplo_grape_api/app/views/contatos/_form.html.erb
<%= form_for(@contato) do |f| %>
  <% if @contato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contato.errors.count, "error") %> prohibited this contato from being saved:</h2>

      <ul>
      <% @contato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :operadora_id %><br>
    <%= f.text_field :operadora_id %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.datetime_select :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

exemplo_grape_api/app/views/contatos/edit.html.erb
<h1>Editing contato</h1>

<%= render 'form' %>

<%= link_to 'Show', @contato %> |
<%= link_to 'Back', contatos_path %>

exemplo_grape_api/app/views/contatos/index.html.erb
<h1>Listing contatos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Telefone</th>
      <th>Operadora</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contatos.each do |contato| %>
      <tr>
        <td><%= contato.nome %></td>
        <td><%= contato.telefone %></td>
        <td><%= contato.operadora %></td>
        <td><%= contato.data %></td>
        <td><%= link_to 'Show', contato %></td>
        <td><%= link_to 'Edit', edit_contato_path(contato) %></td>
        <td><%= link_to 'Destroy', contato, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contato', new_contato_path %>

exemplo_grape_api/app/views/contatos/new.html.erb
<h1>New contato</h1>

<%= render 'form' %>

<%= link_to 'Back', contatos_path %>

exemplo_grape_api/app/views/contatos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @contato.nome %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @contato.telefone %>
</p>

<p>
  <strong>Operadora:</strong>
  <%= @contato.operadora %>
</p>

<p>
  <strong>Data:</strong>
  <%= @contato.data %>
</p>

<%= link_to 'Edit', edit_contato_path(@contato) %> |
<%= link_to 'Back', contatos_path %>

exemplo_grape_api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExemploGrapeApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

exemplo_grape_api/app/views/operadoras/_form.html.erb
<%= form_for(@operadora) do |f| %>
  <% if @operadora.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operadora.errors.count, "error") %> prohibited this operadora from being saved:</h2>

      <ul>
      <% @operadora.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :codigo %><br>
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :categoria %><br>
    <%= f.text_field :categoria %>
  </div>
  <div class="field">
    <%= f.label :preco %><br>
    <%= f.text_field :preco %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

exemplo_grape_api/app/views/operadoras/edit.html.erb
<h1>Editing operadora</h1>

<%= render 'form' %>

<%= link_to 'Show', @operadora %> |
<%= link_to 'Back', operadoras_path %>

exemplo_grape_api/app/views/operadoras/index.html.erb
<h1>Listing operadoras</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Codigo</th>
      <th>Categoria</th>
      <th>Preco</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @operadoras.each do |operadora| %>
      <tr>
        <td><%= operadora.nome %></td>
        <td><%= operadora.codigo %></td>
        <td><%= operadora.categoria %></td>
        <td><%= operadora.preco %></td>
        <td><%= link_to 'Show', operadora %></td>
        <td><%= link_to 'Edit', edit_operadora_path(operadora) %></td>
        <td><%= link_to 'Destroy', operadora, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Operadora', new_operadora_path %>

exemplo_grape_api/app/views/operadoras/new.html.erb
<h1>New operadora</h1>

<%= render 'form' %>

<%= link_to 'Back', operadoras_path %>

exemplo_grape_api/app/views/operadoras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @operadora.nome %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @operadora.codigo %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @operadora.categoria %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @operadora.preco %>
</p>

<%= link_to 'Edit', edit_operadora_path(@operadora) %> |
<%= link_to 'Back', operadoras_path %>